services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5439:5432"
  adminer:
    image: adminer
    ports:
      - "8032:8080"

volumes:
  postgres_data:
